config/routes.rb
Rails.application.routes.draw do
  get '/home',  to: 'static_pages#home'

  get '/help',  to: 'static_pages#help'

  get '/about',  to: 'static_pages#about'

  root 'static_pages#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def hello
    render html: "hello world!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | 4Members</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->
  
  
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand whitext" href="#">Brand</a>
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Log in", '#' %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
    
  <%= yield %>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About" ) %>
<!DOCTYPE html>
<html>
  <head>
    
  </head>
  <body>
    <h1>About</h1>
    <p>Everything you need to know about the app!</p>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <head>
    
  </head>
  
  <body>
    <h1>Help</h1>
    <p>Contact us for any help u might need with the app!</p>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home" ) %>
<!DOCTYPE html>
<html>
  <head>
    
  </head>
  
  <body>
    <div class="center jumbotron">
      <h1 class="text-center">4Members</h1>
      <p class="text-center">Hello this is a Members Only App.You have to be registered to find out who is saying what!Welcome and have fun :)</p>
      <div class="text-center">
        <button type="button" class="btn btn-primary">Sign Up Now!</button>
      </div>
    </div>
  </body>
</html>